import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import Feed from "../components/Feed/Feed";
import LeftSidebar from "../components/LeftSidebar/LeftSidebar";
import Login from "../components/Login/Login";
import Navbar from "../components/Navbar/Navbar";
import RightSidebar from "../components/RightSidebar/RightSidebar";

export default function Home() {

  const { data: session } = useSession();

  if(!session) return <Login />
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Navbar />
      <LeftSidebar />
      <RightSidebar />
      <Feed />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

  return {
    props: {
      session,
    }
  }
}
